
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'lm_analytics'
version: '1.0.0'
config-version: 2
#require-dbt-version: '>=1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'lm_analytics'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
tests:
  +store_failures: true
seeds:
  +schema: source
  +full_refresh: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
# models:
#   lm_analytics:
#     # Config indicated by + and applies to all files under models/example/
#     2_lm_stage_vault:
#       +materialized: view
#       +schema: stage_vault
#     3_lm_raw_vault:
#       +materialized: incremental
#       +schema: raw_vault
#     # 4_lm_bus_vault:
#     #   +materialized: table
#     #   +schema: bus_vault
#     5_lm_mart:
#       +materialized: table 
#       +schema: mart